#!name=ampDache
#!desc=高德打车签到cookie
#!date=2025-04-24 22:29:59

[Script]
ampDache = type=http-response, pattern=^https?:\/\/(m5(|-zb)|dache)\.amap\.com\/(ws\/yuece\/(act|openapi\/activity\/current)\/query|common\/(alipaymini|wxmini)\?_ENCRYPT=), script-path=https://raw.githubusercontent.com/wf021325/qx/master/task/ampDache.js, requires-body=true, max-size=-1, timeout=60

高德地图打车签到 = type=cron, cronexp=1 0 * * *, script-path=https://raw.githubusercontent.com/wf021325/qx/master/task/ampDache.js, timeout=120, wake-system=1

[MITM]
hostname = %APPEND% *.amap.com
