#!name=ChinaMobile
#!desc=中国移动去广告

[Rule]
# > 中国移动
IP-CIDR,120.240.95.37/32,REJECT

[URL Rewrite]
# > 中国移动
^https?:\/\/client\.app\.coc\.10086\.cn\/biz-orange\/DN\/init\/startInit - reject
^https?:\/\/client\.app\.coc\.10086\.cn\/biz-orange\/DN\/explorePage\/getAdverList - reject
# 多个悬浮窗
^https?:\/\/(client\.app\.coc|app)\.10086\.cn\/biz-orange\/DN\/emotionMarket - reject

[MITM]
hostname = %APPEND% client.app.coc.10086.cn, app.10086.cn
