#!name=sfsy_token
#!desc=顺丰速运获取token
#!author=yangchong99 by Slkiss
#!icon=https://raw.githubusercontent.com/Sliverkiss/QuantumultX/main/icon/Sfsy.png
#!homepage=https://raw.githubusercontent.com/yangchong99/Loon/main/plugin/sfsy_token.plugin
#!update=2025-04-30 15:30:08

[Script]
顺丰速运获取token = type=http-response, pattern=^https:\/\/mcs-mimp-web\.sf-express\.com\/mcs-mimp\/share\/weChat\/shareGiftReceiveRedirect.+, script-path=https://raw.githubusercontent.com/Moli-X/Resources/main/Script/Sfsy.js, requires-body=true, timeout=60

[MITM]
hostname = %APPEND% mcs-mimp-web.sf-express.com
