#!name=wechat_pay_coupon
#!desc=微信支付有优惠-领金币,每周累计使用微信支付 10 次可领取 15 金币,添加重写进入"微信支付有优惠"小程序即可获取 Token，支持多账号，仅支持 NE 环境
#!date=2025-04-24 22:33:52

[MITM]
hostname = payapp.weixin.qq.com

[Script]
微付金币² = type=http-response,pattern=https:\/\/payapp\.weixin\.qq\.com\/(coupon-center-user\/home\/login|coupon-center-award\/award\/detail),requires-body=1,max-size=0,binary-body-mode=0,timeout=30,script-path=https://raw.githubusercontent.com/FoKit/Scripts/main/scripts/wechat_pay_coupon.js,script-update-interval=0

微付金币 = type=cron,cronexp=30 9 * * *,timeout=60,script-path=https://raw.githubusercontent.com/FoKit/Scripts/main/scripts/wechat_pay_coupon.js,script-update-interval=0
